services:
  postgres:
    image: samagragovernance/postgres:1.0.1-pg15
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - dataset-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  dataset-db:
    