services:
  postgres:
    image: samagragovernance/postgres:1.0.1-pg15
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - dataset-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_USERNAME} ${MINIO_PASSWORD};
      /usr/bin/mc rm -r --force myminio/${MINIO_BUCKETNAME};
      /usr/bin/mc mb myminio/${MINIO_BUCKETNAME};
      /usr/bin/mc anonymous set public myminio/${MINIO_BUCKETNAME};
      exit 0;
      "

volumes:
  dataset-db:
  minio-data: